### ISSUE TITLE
Ubuntu 20.04 dependencies...

### ISSUE THREAD

**Issue by Creteil** [dicetrash/qusbipserver#1]
Hi,

Can you change your dependencies « control » file for :

```
Package: qusbipserver
Version: 1.0
Section: custom
Priority: optional
Architecture: all
Files: *
Copyright: 2020 dicetrash
License: GPL-2+
Essential: no
Installed-Size: 1024
Maintainer: dicetrash
Build-Depends:
 build-essential
 libudev-dev
 qtdeclarative5-dev
 dh-systemd
Depends: libudev1,
 usbip | linux-tools-generic,
 libqt5network5
Description: A server admin for attaching usb over ip between linux devices.
```

« usbip **| linux-tools-generic**, »

On Ubuntu, « usbip » binary depend from « linux-tools-generic »...

Maybe you will find something more elegant, at least this trick seem to work on my side...

Regards

**Comment by dicetrash** [comment]
Id rather take MRs or maintainers .. I don't actually run ubuntu, I just figured it was so widely used I should have SOMETHING for it.

**Comment by dicetrash** [comment]
Thanks for this, I didn't realize ubuntu and debian had different base packages for the same materials, I use the docker images to build and verify these.  .. now all I need is a build server to repackage everything >.<

**Comment by dicetrash** [comment]
https://github.com/dicetrash/qusbipserver/commit/5b8be5962d72030db241757e65b178f6b9a6717a commited, will rebuild in a couple
